### ptroch 自动微分
* autograd 软件包为Tensors上的所有操作提供自动微分
* 它是一个由运行定义的框架
 * 意味着以代码运行方式定义你的后向传播，并且每次迭代都可以不同
#### TENSOR
* torch.Tensor 是包的核心类。
  * 如果将其属性 .requires_grad 设置为 True，则会开始跟踪针对 tensor 的所有操作。
  * 完成计算后，您可以调用 .backward() 来自动计算所有梯度。该张量的梯度将累积到 .grad 属性中。
* 要停止 tensor 历史记录的跟踪，您可以调用 .detach()，它将其与计算历史记录分离，并防止将来的计算被跟踪。
* 停止跟踪历史记录（和使用内存），您还可以将代码块使用 with torch.no_grad(): 包装起来。在评估模型时，这是特别有用，因为模型在训练阶段具有 requires_grad = True 的可训练参数有利于调参，但在评估阶段我们不需要梯度。
* Function
  * Tensor 和 Function 互相连接并构建一个非循环图，它保存整个完整的计算过程的历史信息
  * 每个张量都有一个 .grad_fn 属性保存着创建了张量的 Function 的引用，（如果用户自己创建张量，则g rad_fn 是 None ）
* Tensor.backward()
  * 计算导数
  * Tensor 是标量（即它包含一个元素数据），则不需要指定任何参数backward()，但是如果它有更多元素，则需要指定一个gradient 参数来指定张量的形状

In [2]:
import torch

In [10]:
# 创建一个张量，设置require_grad = True 来跟踪与它相关的计算
x = torch.ones(2,2,requires_grad = True)
print(x)

y=x+2
print(y)
print(y.grad_fn)

z = y*y*3
out=z.mean()
print(z,out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [11]:
# .requires_grad_( ... ) 会改变张量的 requires_grad 标记。输入的标记默认为 False ，如果没有提供相应的参数
a=torch.randn(2,2)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

del a,b

False
True


In [13]:
# 梯度
# 后向传播
out.backward()
print(x.grad)

del x,y,z,out

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [9]:
# 雅可比向量积
x=torch.randn(3,requires_grad=True)
print(x)
y=x*2
print(y)
while y.data.norm() <1000:
    y=y*2
print(y)

tensor([-1.3887,  1.2233,  1.3086], requires_grad=True)
tensor([-2.7775,  2.4465,  2.6171], grad_fn=<MulBackward0>)
tensor([-711.0353,  626.3071,  669.9870], grad_fn=<MulBackward0>)
