### Tensor(张量)
Tensor可以使用GPU计算

In [2]:
from __future__ import print_function 
#用比当前版本更新的版本的print函数
#如果某个版本中出现了某个新的功能特性，而且这个特性和当前版本中使用的不兼容，也就是它在该版本中不是语言标准，那么我如果想要使用的话就需要从future模块导入
import torch

### torch.empty()
创建的矩阵不是空矩阵，而是未初始化的矩阵，所以里面的值不一定为0
### torch.rand()
rand方法生成的是一个用随机数初始化的矩阵，里面的数值为限定时是在[0,1]之间随机生成
### torch.zeros()
生成0矩阵，detype参数指定了生成的数据的类型

In [22]:
#构造一个5*3的矩阵，不初始化
x = torch.empty(5, 3)
print(x)
del x

#构造一个随机初始化的矩阵
x = torch.rand(4, 3)
print(x)
del x

#零矩阵
x = torch.zeros(4,2,dtype=torch.long)
print(x)
del x


tensor([[9.2755e-39, 1.0561e-38, 9.9184e-39],
        [9.7347e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39]])
tensor([[0.8130, 0.5629, 0.5941],
        [0.9352, 0.1794, 0.6543],
        [0.3154, 0.9947, 0.6330],
        [0.1798, 0.7803, 0.7325]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [47]:
#构建一个张量，直接使用数据
x = torch.tensor([[5.5,3],[1,3.2],[1,7]])
print(x)

#创建一个tensor基于已经存在的tensor
x = x.new_ones(5, 3, dtype=torch.double)  # new_* methods take in sizes
print(x)
# override dtype!
x = torch.rand_like(x, dtype=torch.float)
print(x)

# 获取维度信息
print(x.size())
del x


tensor([[5.5000, 3.0000],
        [1.0000, 3.2000],
        [1.0000, 7.0000]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.8848, 0.5209, 0.1145],
        [0.1268, 0.4456, 0.3377],
        [0.7568, 0.5200, 0.9009],
        [0.3830, 0.0472, 0.4234],
        [0.2528, 0.5404, 0.1748]])
torch.Size([5, 3])


In [36]:
# 加法操作
# 法1
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x + y)

#法2
print(torch.add(x,y))

#提供一个输出tensor作为参数
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

# in-place
# 任何使张量会发生变化的操作都有一个前缀 ‘’。例如：x.copy(y), x.t_(), 将会改变 x.
# 在提供的方法中，如果是(operation)_ (arg)格式的方法的，操作后会替换到调用这个方法的对象
print(y.add_(x))

del x, y

tensor([[0.9677, 1.1536, 0.7954],
        [0.7877, 1.1503, 1.2650],
        [1.4950, 1.7915, 1.4434],
        [0.6947, 1.0385, 0.6153],
        [0.4239, 1.5729, 0.9048]])
tensor([[0.9677, 1.1536, 0.7954],
        [0.7877, 1.1503, 1.2650],
        [1.4950, 1.7915, 1.4434],
        [0.6947, 1.0385, 0.6153],
        [0.4239, 1.5729, 0.9048]])
tensor([[0.9677, 1.1536, 0.7954],
        [0.7877, 1.1503, 1.2650],
        [1.4950, 1.7915, 1.4434],
        [0.6947, 1.0385, 0.6153],
        [0.4239, 1.5729, 0.9048]])
tensor([[0.9677, 1.1536, 0.7954],
        [0.7877, 1.1503, 1.2650],
        [1.4950, 1.7915, 1.4434],
        [0.6947, 1.0385, 0.6153],
        [0.4239, 1.5729, 0.9048]])


In [49]:
#  使用标准的 NumPy 类似的索引操作
x = torch.rand(5, 3)
print(x)
print(x[:,1]) # 第1列
print(x[1,:]) # 第1行
del x

tensor([[0.3950, 0.6389, 0.0863],
        [0.2486, 0.8204, 0.4562],
        [0.5468, 0.7040, 0.6605],
        [0.6142, 0.3195, 0.6183],
        [0.3570, 0.1794, 0.0146]])
tensor([0.6389, 0.8204, 0.7040, 0.3195, 0.1794])
tensor([0.2486, 0.8204, 0.4562])
tensor([[-2.0958, -0.6813,  1.1618, -1.1959],
        [-0.1138,  2.2025,  0.9592, -1.2419],
        [ 1.5466,  0.2691, -0.0165, -0.7713],
        [-0.2043, -1.5196,  0.7298,  1.3535]])
tensor([-2.0958, -0.6813,  1.1618, -1.1959, -0.1138,  2.2025,  0.9592, -1.2419,
         1.5466,  0.2691, -0.0165, -0.7713, -0.2043, -1.5196,  0.7298,  1.3535])


In [57]:
#改变大小:如果你想改变一个 tensor 的大小或者形状，你可以使用 torch.view
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(2,8)  #the size -1 is inferred from other dimensions
print(z)
print(x.size(),y.size(),z.size())
del x, y, z

tensor([[-0.8866,  2.8248,  1.2147,  1.3770],
        [ 1.1848, -0.0169, -0.8084, -0.7689],
        [-0.7298, -1.6150, -0.4577,  0.8436],
        [ 0.2294, -0.3432, -0.3540,  1.0920]])
tensor([-0.8866,  2.8248,  1.2147,  1.3770,  1.1848, -0.0169, -0.8084, -0.7689,
        -0.7298, -1.6150, -0.4577,  0.8436,  0.2294, -0.3432, -0.3540,  1.0920])
tensor([[-0.8866,  2.8248,  1.2147,  1.3770,  1.1848, -0.0169, -0.8084, -0.7689],
        [-0.7298, -1.6150, -0.4577,  0.8436,  0.2294, -0.3432, -0.3540,  1.0920]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [61]:
# 有一个元素 tensor ，使用 .item() 来获得这个 value
# only one element tensors can be converted to Python scalars
x = torch.rand(1)
print(x)
print(x.item())
del x

tensor([0.1897])
0.1897328495979309


In [3]:
# permute
x=torch.randn(2,3,5)
print(x)
print(x.permute(2,0,1))
del x

tensor([[[ 0.1819,  0.8817,  0.4453, -0.2474,  0.1320],
         [-2.3574, -0.6190, -0.5267, -0.2791,  0.1742],
         [-1.1595, -0.4749, -0.6572, -0.8144,  0.8769]],

        [[ 1.3520, -0.0215,  1.0156, -0.4210, -0.3527],
         [ 1.5945,  0.7555,  0.9375,  1.1207,  0.1146],
         [ 0.0446, -1.4067, -0.3766, -0.1404, -0.6249]]])
tensor([[[ 0.1819, -2.3574, -1.1595],
         [ 1.3520,  1.5945,  0.0446]],

        [[ 0.8817, -0.6190, -0.4749],
         [-0.0215,  0.7555, -1.4067]],

        [[ 0.4453, -0.5267, -0.6572],
         [ 1.0156,  0.9375, -0.3766]],

        [[-0.2474, -0.2791, -0.8144],
         [-0.4210,  1.1207, -0.1404]],

        [[ 0.1320,  0.1742,  0.8769],
         [-0.3527,  0.1146, -0.6249]]])


In [7]:
# size
x = torch.rand(2,3,5)
print(x)
size = x.size()[1:]
print(size)
num_features = 1
for s in size :
    num_features *= s
    print(s,num_features)
print(x.view(-1,num_features))


tensor([[[0.1398, 0.1241, 0.8804, 0.5725, 0.4980],
         [0.3978, 0.4305, 0.7748, 0.2540, 0.6507],
         [0.4657, 0.7460, 0.3016, 0.4784, 0.5737]],

        [[0.3954, 0.4639, 0.3829, 0.4042, 0.3835],
         [0.3311, 0.7268, 0.7097, 0.6762, 0.2821],
         [0.8117, 0.8426, 0.1421, 0.3624, 0.8337]]])
torch.Size([3, 5])
3 3
5 15
tensor([[0.1398, 0.1241, 0.8804, 0.5725, 0.4980, 0.3978, 0.4305, 0.7748, 0.2540,
         0.6507, 0.4657, 0.7460, 0.3016, 0.4784, 0.5737],
        [0.3954, 0.4639, 0.3829, 0.4042, 0.3835, 0.3311, 0.7268, 0.7097, 0.6762,
         0.2821, 0.8117, 0.8426, 0.1421, 0.3624, 0.8337]])
