In [1]:
from __future__ import print_function
import torch
from torch import tensor

In [8]:
print('This is test -> ',end='') # 不换行
print('hhhh')

a = torch.randn(4,2,2,3)
print(a)

This is test -> hhhh
tensor([[[[-0.2107,  0.9076, -0.4736],
          [ 1.1513, -2.0999, -1.4710]],

         [[ 1.9903,  1.2881,  0.2106],
          [ 0.6337, -1.8029, -0.5580]]],


        [[[-0.0852,  0.8813,  0.9911],
          [-2.1323,  0.1359,  1.5391]],

         [[ 0.6895,  1.7880,  0.1829],
          [ 1.0341, -0.8454, -0.6233]]],


        [[[-0.5648,  0.4411,  0.9810],
          [-1.2038, -0.0420, -1.0039]],

         [[-1.1804, -0.8301, -0.2067],
          [-0.6199, -0.9497, -1.4524]]],


        [[[ 0.3261, -0.2439,  1.8939],
          [ 0.1056, -0.5177, -0.6663]],

         [[-0.9355, -0.5261, -0.6409],
          [ 0.9625, -0.5376, -1.5680]]]])


In [18]:
window_size = (2,2)
coords_h = torch.arange(window_size[0])
coords_w = torch.arange(window_size[1])
coords = torch.stack(torch.meshgrid([coords_h, coords_w]))
coords_flatten = torch.flatten(coords, 1)

relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :] # 2, Wh * Ww, Wh * Ww
relative_coords = relative_coords.permute(1, 2, 0).contiguous()  # Wh*Ww, Wh*Ww, 2
relative_coords[:, :, 0] += window_size[0] -1 # h: shift to start from 0 在高度上离当前位置最远的距离为 （self.window_size[0] -1）
relative_coords[:, :, 1] += window_size[1] -1 # w:
relative_coords[:, :, 0] *= 2 * window_size[1] -1
relative_position_index = relative_coords.sum(-1) # Wh*Ww, Wh*Ww 在最后一维上求和，展开成一个 1D 坐标
#print(coords_h)
#print(coords_w)
#print(torch.meshgrid([coords_h, coords_w]))
#print(coords)
#print(coords_flatten)
print(coords_flatten[:, :, None])
print(coords_flatten[:, None, :])
print(relative_coords)
print(relative_coords.permute(1, 2, 0))
print(relative_position_index)

tensor([[[0],
         [0],
         [1],
         [1]],

        [[0],
         [1],
         [0],
         [1]]])
tensor([[[0, 0, 1, 1]],

        [[0, 1, 0, 1]]])
tensor([[[3, 1],
         [3, 0],
         [0, 1],
         [0, 0]],

        [[3, 2],
         [3, 1],
         [0, 2],
         [0, 1]],

        [[6, 1],
         [6, 0],
         [3, 1],
         [3, 0]],

        [[6, 2],
         [6, 1],
         [3, 2],
         [3, 1]]])
tensor([[[3, 3, 6, 6],
         [1, 2, 1, 2]],

        [[3, 3, 6, 6],
         [0, 1, 0, 1]],

        [[0, 0, 3, 3],
         [1, 2, 1, 2]],

        [[0, 0, 3, 3],
         [0, 1, 0, 1]]])
tensor([[4, 3, 1, 0],
        [5, 4, 2, 1],
        [7, 6, 4, 3],
        [8, 7, 5, 4]])


In [20]:
a = torch.randn(2,3)
print(a)
print(a.view(-1))

tensor([[ 1.6898, -0.5122,  0.4998],
        [-1.2352,  1.7703,  0.5849]])
tensor([ 1.6898, -0.5122,  0.4998, -1.2352,  1.7703,  0.5849])
