In [1]:
import einops
import torch

x=torch.randn(1,2,3,4)
print(x)
x=einops.rearrange(x,"b c h w -> b h (c w)")
print(x)
print(x[:,0])

tensor([[[[ 0.8592, -1.5519, -1.1331,  0.2478],
          [ 1.6175,  1.9244, -1.9487, -1.0057],
          [-0.1172, -0.8962, -1.1660, -0.1693]],

         [[ 0.3320, -0.0628, -0.6673, -0.3221],
          [ 1.1409,  0.5191, -1.2132,  1.4107],
          [-0.9285, -0.6838, -1.5626, -1.4731]]]])
tensor([[[ 0.8592, -1.5519, -1.1331,  0.2478,  0.3320, -0.0628, -0.6673,
          -0.3221],
         [ 1.6175,  1.9244, -1.9487, -1.0057,  1.1409,  0.5191, -1.2132,
           1.4107],
         [-0.1172, -0.8962, -1.1660, -0.1693, -0.9285, -0.6838, -1.5626,
          -1.4731]]])
tensor([[ 0.8592, -1.5519, -1.1331,  0.2478,  0.3320, -0.0628, -0.6673, -0.3221]])
